on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '2.7'       
      - name: get_val
        env: 
          SPECIAL_KEY: ${{ secrets.FOURK_KEY2 }} 
        run: |
          pip install requests 
          python request.py
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # -- Build your project here -- eg. mvn clean package
      - name: Synopsys Detect
        uses: blackducksoftware/github-action@v2.2
        with:
          blackduck.url: ${{ secrets.BLACKDUCK_URL }}
          blackduck.api.token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          args: '--detect.risk.report.pdf=true --blackduck.trust.cert=true'
